config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  get 'home/index'

  resources :receipes	

  #root 'users/sessions#new'
  root :to => redirect("/users/sign_in")


 devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/receipe.rb
class Receipe < ApplicationRecord
	has_many :ingredients, dependent: :destroy
	accepts_nested_attributes_for :ingredients

	has_many :receipe_photos, dependent: :destroy
	accepts_nested_attributes_for :receipe_photos

	validates :name, presence: true,
                    length: { minimum: 5 }

end

app/controllers/receipes_controller.rb
class ReceipesController < ApplicationController
  skip_before_action :authenticate_user!,only: [:index, :show]
  def index
    if params[:ingred].present?
  	 @receipes = Receipe.select{|rec| rec.ingredients.map(&:ingred).include?(params[:ingred])}
    else
      @receipes = Receipe.all.order('created_at DESC, id DESC')
    end
  end

  def show
    @receipe = Receipe.find(params[:id])
  end

  def new
  	@receipe = Receipe.new
    @receipe.ingredients.new
    @receipe.receipe_photos.new
  end

  def edit
    @receipe = Receipe.find(params[:id])
  end

  def update
	  @receipe = Receipe.find(params[:id])
	 
	  if @receipe.update(receipe_params)
	    redirect_to @receipe
	  else
	    render 'edit'
	  end
  end

  def destroy
    @receipe = Receipe.find(params[:id])
    @receipe.destroy
 
    redirect_to receipes_path
  end


  def create
  	@receipe = Receipe.new(receipe_params)
	  if @receipe.save
	    redirect_to @receipe
	  else
	    render 'new'
	  end
  end


  private
  def receipe_params
    params.require(:receipe).permit(:name, :description, ingredients_attributes: [:receipe_id, :ingred], receipe_photos_attributes: [:id, :receipe_id, :photo])
  end
end

app/helpers/receipes_helper.rb
module ReceipesHelper
end

app/views/receipes/_form.html.erb
<%= form_with model: @receipe, local: true do |form| %>
 
  <% if @receipe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@receipe.errors.count, "error") %> prohibited
        this receipe from being saved:
      </h2>
      <ul>
        <% @receipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <%= form.nested_fields_for :ingredients do |builder| %>
    <p>
      <%= builder.label :ingredients %>
      <%= builder.text_field :ingred %>
      <%= builder.remove_nested_fields_link 'Remove me'%>
    </p>
  <% end %>
  <%= form.add_nested_fields_link :ingredients , 'Add another ingredient' %>
  <%= form.nested_fields_for :receipe_photos do |image| %>
    <p>
      <%= image.label :receipe_photos %>
      <%= image.file_field :photo %>
      <%= image.remove_nested_fields_link 'Remove me'%>
    </p>
  <% end %>
 <%= form.add_nested_fields_link :receipe_photos , 'Add another photo' %>
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/receipes/edit.html.erb
<h1>Edit Food Receipe</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', receipes_path %>

app/views/receipes/index.html.erb
<%  unless current_user.guest? %>
  <%= link_to 'New Receipe', new_receipe_path %> <br/>
  <%= link_to 'Receipes', receipes_path %></br>
<% end %>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>  
<% end %>

<h1>Listing of Food Receipe!</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Descrption</th>
    <th>Ingredients</th>
    <th colspan="2"></th>
  </tr>
 
  <% @receipes.each do |receipe| %>
    <tr>
      <td><%= receipe.name %></td>
      <td><%= receipe.description %></td>
      <td><%= receipe.ingredients.map(&:ingred).join(",") %></td>
      <td>
        <% if receipe.receipe_photos.present? %>
          <%- receipe.receipe_photos.each do |p|%>
            <%= image_tag p.photo.try(:url), :width=>"40", :height=>"40"%>
          <% end %>
        <% end %>
      </td>
      <%  unless current_user.guest? %>
        <td><%= link_to 'Show', receipe_path(receipe) %></td>
        <td><%= link_to 'Edit', edit_receipe_path(receipe) %></td>
         <td><%= link_to 'Destroy', receipe_path(receipe),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/receipes/new.html.erb
<h1>New Food Receipe</h1>

<%= render 'form' %>




<%= link_to 'Back', receipes_path %>

app/views/receipes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @receipe.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @receipe.description %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @receipe.ingredients.map(&:ingred).join(",") %>
</p>

<%#= link_to 'Back', receipes_path(receipe) %>
<%= link_to 'Edit', edit_receipe_path(@receipe) %> |
<%= link_to 'Back', receipes_path %>